{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "83dd9bb6_06150c9a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 30
      },
      "lineNbr": 0,
      "author": {
        "id": 411
      },
      "writtenOn": "2025-02-28T11:34:06Z",
      "side": 1,
      "message": "nothing changed, the same connection issue after reboot https://logserver.rdoproject.org/03/56203/2/check/periodic-adoption-multinode-to-crc-ceph/f44c18e/overcloud-novacompute-0/log/containers/nova/nova-compute.log",
      "revId": "2868f59fe476a5b779a45add239d6c09eda19ea0",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    }
  ]
}