{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "25902318_35228b0a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 749
      },
      "writtenOn": "2022-09-29T18:50:48Z",
      "side": 1,
      "message": "Testing at https://review.rdoproject.org/r/c/testproject/+/45218",
      "revId": "ba4b849b314af2eb7851a4e848dedd30a601204c",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "0fcf29c1_92b6ebe1",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 192
      },
      "writtenOn": "2022-09-30T05:45:38Z",
      "side": 1,
      "message": "looks right but am not involved at all here\n\n+1 for now adding into to my reviews - fs35 is failing tempest in the review is that a consistent thing (may be related to sdk/version ? tempest.lib.exceptions.UnexpectedContentType: Unexpected content type provided https://logserver.rdoproject.org/18/45218/5/check/tripleo-ci-centos-9-ovb-3ctlr_1comp-featureset035-aco/0008dae/logs/undercloud/var/log/tempest/stestr_results.html.gz ",
      "revId": "ba4b849b314af2eb7851a4e848dedd30a601204c",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "0ce62303_0a0d1ceb",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 671
      },
      "writtenOn": "2022-09-30T10:22:46Z",
      "side": 1,
      "message": "rekicked fs035 on testproject: https://review.rdoproject.org/r/c/testproject/+/45218, lets see if failure is consistent",
      "revId": "ba4b849b314af2eb7851a4e848dedd30a601204c",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    }
  ]
}